# pkgs/plymouth-theme-bauergroup/default.nix
# ─────────────────────────────────────────────────────────────────────
# BAUER GROUP boot splash for Plymouth.
#
# Built from the brand SVG rather than a checked-in PNG, so the raster is
# regenerated whenever the logo or the palette changes and the repository
# carries a diffable asset instead of a binary. Colours come in as hex, the
# canonical notation in the brand guide.
#
# Uses the "script" plugin: one text file draws everything. The alternative,
# "two-step", wants a numbered PNG per animation frame, which is a lot of
# binary for a logo that does not move.
# ─────────────────────────────────────────────────────────────────────
{
  lib,
  runCommand,
  writeText,
  resvg,

  # assets/branding/bauer-group-logo-wide-white.svg — the dark-background
  # lockup: orange mark, white wordmark
  logo,

  # Brand palette. Defaults are tokens from the BAUER GROUP corporate identity:
  #   background  warm-900  "Brand Black"
  #   accent      orange-500 "Brand Primary"
  #   track       warm-800  "Brand Dark"
  #   foreground  warm-50   "Brand Light"
  background ? "#231F1C",
  accent ? "#FF8500",
  track ? "#3A3430",
  foreground ? "#F9F8F6",

  # The SVG masters were converted from EPS and carry percentage rgb() fills
  # that round to #F57E13, not the canonical #FF8500. The brand guide makes hex
  # authoritative for logo files, so the fill is corrected on the way in rather
  # than shipping an off-brand orange on every boot screen in the fleet.
  correctFills ? {
    "rgb(96.186829%, 49.583435%, 7.623291%)" = accent;
  },

  logoWidth ? 1440,
}:
let
  # Plymouth's script plugin takes colour channels as 0..1 floats, while the
  # brand guide speaks hex, so convert here instead of duplicating the palette.
  hexDigits = {
    "0" = 0;
    "1" = 1;
    "2" = 2;
    "3" = 3;
    "4" = 4;
    "5" = 5;
    "6" = 6;
    "7" = 7;
    "8" = 8;
    "9" = 9;
    "a" = 10;
    "b" = 11;
    "c" = 12;
    "d" = 13;
    "e" = 14;
    "f" = 15;
  };

  hexPair =
    hex: offset:
    let
      digit = i: hexDigits.${lib.toLower (lib.substring (offset + i) 1 hex)};
    in
    16 * digit 0 + digit 1;

  # "#RRGGBB" -> { r; g; b; } as float strings
  channels = hex: {
    r = toString (hexPair hex 1 / 255.0);
    g = toString (hexPair hex 3 / 255.0);
    b = toString (hexPair hex 5 / 255.0);
  };

  bg = channels background;
  fg = channels foreground;

  solidSvg =
    colour:
    writeText "solid.svg" ''
      <svg xmlns="http://www.w3.org/2000/svg" width="400" height="8">
        <rect width="400" height="8" fill="${colour}"/>
      </svg>
    '';

  themeScript = writeText "bauergroup.script" ''
    // BAUER GROUP boot splash — generated by pkgs/plymouth-theme-bauergroup.
    // Edit the Nix expression, not this file.

    Window.SetBackgroundTopColor(${bg.r}, ${bg.g}, ${bg.b});
    Window.SetBackgroundBottomColor(${bg.r}, ${bg.g}, ${bg.b});

    screen_width = Window.GetWidth();
    screen_height = Window.GetHeight();

    // ── Logo ──────────────────────────────────────────────────────────
    // A third of the screen width, but never enlarged past the raster: an
    // upscaled wordmark looks worse than a small sharp one, and the brand
    // guide sets a 160 px floor for the wide lockup anyway.
    logo.original = Image("logo.png");
    logo.width = screen_width * 0.34;
    if (logo.width > logo.original.GetWidth())
      {
        logo.width = logo.original.GetWidth();
      }
    logo.scale = logo.width / logo.original.GetWidth();
    logo.image = logo.original.Scale(logo.original.GetWidth() * logo.scale,
                                     logo.original.GetHeight() * logo.scale);
    logo.x = (screen_width - logo.image.GetWidth()) / 2;
    logo.y = (screen_height - logo.image.GetHeight()) / 2 - screen_height * 0.06;

    logo.sprite = Sprite(logo.image);
    logo.sprite.SetX(logo.x);
    logo.sprite.SetY(logo.y);
    logo.sprite.SetZ(1);

    // ── Progress bar ──────────────────────────────────────────────────
    bar.width = screen_width * 0.20;
    bar.height = 4;
    bar.x = (screen_width - bar.width) / 2;
    bar.y = logo.y + logo.image.GetHeight() + screen_height * 0.08;

    bar.track = Sprite(Image("bar-track.png").Scale(bar.width, bar.height));
    bar.track.SetX(bar.x);
    bar.track.SetY(bar.y);
    bar.track.SetZ(1);

    bar.fill_source = Image("bar-fill.png");
    bar.fill = Sprite();
    bar.fill.SetX(bar.x);
    bar.fill.SetY(bar.y);
    bar.fill.SetZ(2);

    fun on_boot_progress(duration, progress)
      {
        width = bar.width * progress;
        // Scale() to zero width is undefined; keep one column instead
        if (width < 1)
          {
            width = 1;
          }
        bar.fill.SetImage(bar.fill_source.Scale(width, bar.height));
      }
    Plymouth.SetBootProgressFunction(on_boot_progress);

    // ── Status line ───────────────────────────────────────────────────
    status.sprite = Sprite();
    status.y = bar.y + screen_height * 0.05;

    fun show_status(text)
      {
        status.image = Image.Text(text, ${fg.r}, ${fg.g}, ${fg.b});
        status.sprite.SetImage(status.image);
        status.sprite.SetX((screen_width - status.image.GetWidth()) / 2);
        status.sprite.SetY(status.y);
        status.sprite.SetZ(3);
      }

    Plymouth.SetMessageFunction(show_status);

    // ── Password prompt ───────────────────────────────────────────────
    // Plymouth hides the console prompt while it is up. Without this a machine
    // with an encrypted root shows a logo and nothing else, and reads as hung
    // to whoever is standing in front of it.
    fun on_password(prompt, bullets)
      {
        dots = "";
        i = 0;
        while (i < bullets)
          {
            dots = dots + "*";
            i = i + 1;
          }
        show_status(prompt + " " + dots);
      }
    Plymouth.SetDisplayPasswordFunction(on_password);

    fun on_normal()
      {
        show_status("");
      }
    Plymouth.SetDisplayNormalFunction(on_normal);

    fun on_quit()
      {
        logo.sprite.SetOpacity(0);
        bar.track.SetOpacity(0);
        bar.fill.SetOpacity(0);
        status.sprite.SetOpacity(0);
      }
    Plymouth.SetQuitFunction(on_quit);
  '';

  fixFills = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (
      from: to:
      "substituteInPlace logo.svg --replace-fail ${lib.escapeShellArg from} ${lib.escapeShellArg to}"
    ) correctFills
  );
in
runCommand "plymouth-theme-bauergroup"
  {
    nativeBuildInputs = [ resvg ];
    meta = {
      description = "BAUER GROUP Plymouth boot splash";
      # No license attribute on purpose. The mark is BAUER GROUP's own, so
      # there is nothing to license from a third party, and declaring it
      # unfree would make the splash fail to build on any template that does
      # not already set allowUnfree. Do not push this package to a public
      # binary cache: it carries the trademark.
      platforms = lib.platforms.linux;
    };
  }
  ''
    theme=$out/share/plymouth/themes/bauergroup
    mkdir -p "$theme"

    # --replace-fail, so a logo whose fills were fixed upstream fails the build
    # here rather than silently skipping the correction
    cp ${logo} logo.svg
    chmod +w logo.svg
    ${fixFills}

    resvg --width ${toString logoWidth} logo.svg "$theme/logo.png"
    resvg ${solidSvg accent} "$theme/bar-fill.png"
    resvg ${solidSvg track} "$theme/bar-track.png"

    cp ${themeScript} "$theme/bauergroup.script"

    # Absolute store paths on purpose: the NixOS plymouth module rewrites any
    # /nix/store/.../share/plymouth/themes prefix to the initrd location when it
    # assembles the initrd, and relative paths are not resolved there.
    cat > "$theme/bauergroup.plymouth" <<EOF
    [Plymouth Theme]
    Name=BAUER GROUP
    Description=BAUER GROUP boot splash
    ModuleName=script

    [script]
    ImageDir=$theme
    ScriptFile=$theme/bauergroup.script
    EOF
  ''
