name: 🧹 CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "LICENSE"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: 🔎 Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: ❄️ Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      - name: 🔎 statix + deadnix
        run: nix build .#checks.x86_64-linux.lint --no-link
